export { default as Analytics } from './Analytics';
export { default as Calendar } from './Calendar';
export { default as Home } from './Home';
export { default as Kanban } from './Kanban';
export { default as Logs } from './Logs';
export { default as Team } from './Team';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Projects } from './Projects';